version: "3"

volumes:
  spotiflypgdata:

services:
  spotiflypostgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - spotiflypgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  spotiflyweb:
    restart: always
    build: .
    image: spotifly
    command: gunicorn music.wsgi:application -b "0.0.0.0:8000"
    # expose:
    #   - "8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - spotiflypostgres