version: "3"

volumes:
  spotiflypgdata:

services:
  # nginx:
  #   image: nginx:1.15-alpine
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - spotiflyweb
  #   volumes:
  #     - ./data/nginx:/etc/nginx/conf.d
  # spotiflypostgres:
  #   restart: always
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - spotiflypgdata:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  spotiflyweb:
    restart: always
    build: .
    image: thatcherthornberry/spotifly:latest
    command: gunicorn music.wsgi:application --bind 0.0.0.0:8001
    expose:
      - "8001"
    env_file:
      - .env
networks:
  default:
    external: true
    name: thatcherthornberry